### ISSUE TITLE
May we have 32-bit version releases?

### ISSUE THREAD

**Issue by aydybb** [intika/Librefox-Firefox#10]
I noticed that all releases can only work on 64-bit platforms, but sometimes we may have to run firefox on 32-bit ones. It would be prefect if Librefox can run on 32-bit OSes!

**Comment by intika** [comment]
I thought i can skip this lol 
okay i will add 32bit on next release its for soon :)

**Comment by aydybb** [comment]
That's great!

**Comment by intika** [comment]
it's done x32 releases are now available for Linux and Windows ;)
