### ISSUE TITLE
Grammar mistakes

### ISSUE THREAD

**Issue by mikroskeem** [intika/Librefox-Firefox#11]
This makes project unappealing for new users. Just saying :smile:

**Comment by mikroskeem** [comment]
Some examples:

* This project aim to fix privacy and security issues related to firefox without **loosing** performances nor forking the project.
* **performances** settings
* Additional **filter** are available

etc.

**Comment by intika** [comment]
Thank you for the feedback it's appreciated... v2 is taking me a lot of time... i just get it done locally today... it will be published today or tomorrow... English is not my first language i am trying the best i can to make the readme as correct as possible, half of what you cited is already corrected in my local version, i will indeed correct what's remaining from your list. 

If you have a little time it would be appreciated if you report back other mistakes once v2 will be published.

Thanks a lot for your contribution. 

Note : i will let you know here when i publish the last version

**Comment by intika** [comment]
I changed `official firefox set for a better privacy, security and performances` to `official firefox with a better privacy, security and performances` can you please develop what was the mistake ?

**Comment by mikroskeem** [comment]
You're welcome, I'll take a look at v2 once it's released and when I have time. :smile:

>what was the mistake ?
In my opinion (and few others) given sentence was badly worded and hard to understand.

**Comment by brainscar** [comment]
I made same spelling changes, feel free to copy :-) I can't submit a pull for some reason.


https://github.com/brainscar/Librefox-Firefox/commit/75ff40466e5b92ae65245971c2ee9d411a1eeed9

**Comment by brainscar** [comment]
Github is malfunctioning on my computer, so I put some spelling changes here:


https://www.diffchecker.com/EqeYzO6D

**Comment by mikroskeem** [comment]
@brainscar can you provide that diff somewhere so one could apply it using e.g `git diff`?

**Comment by brainscar** [comment]
👍 

https://github.com/brainscar/Librefox-Firefox/blob/master/README.md

**Comment by intika** [comment]
Woups i already applied the changes... it does a matter i will PR your version any way :) :+1:

**Comment by intika** [comment]
Changes have been done, closing this.
thanks you a lot for your contribution
