### ISSUE TITLE
Wouldn't gitlab be more appropriate for a "libre" project?

### ISSUE THREAD

**Issue by Zig-03** [intika/Librefox-Firefox#13]

**Comment by intika** [comment]
Thank you for your contribution :) 

Can you please develop ? 

In my point of view both are US Companies and in both cases you don't have access to their server so i don't see the advantage to move to gitlab. almost nothing in the cloud is "Libre"

**Comment by Zig-03** [comment]
Thank you for your reply :)

> Can you please develop ?

What do you mean?

> In my point of view both are US Companies and in both cases you don't have access to their server so i don't see the advantage to move to gitlab. almost nothing in the cloud is "Libre"

gitlab is FOSS and anyone can also host his/her own instance - https://gitlab.com/gitlab-org/gitlab-ce 
So as you can see, this is already a lot more than what github can offer to any foss enthusiasts. Thanks a lot :)

**Comment by intika** [comment]
> What do you mean? 

Was just asking for explanations about your point of view... you already did :)

> gitlab is FOSS and anyone can also host his/her own instance - https://gitlab.com/gitlab-org/gitlab-ce
So as you can see, this is already a lot more than what github can offer to any foss enthusiasts. Thanks a lot :) 

Yes i know but this project is not yet the kind of self hosted project, until then it live here :D where it can reach some peoples ^^ 

Even if its FOSS i think it's just a marketing thing, after all the first purpose of the company is to make money and it's impossible to have access to the running version on their server even if it's probably the same as the published one. 

I just don't see the plus for such a project. But yeah i totally agree with you about the idea and in the FOSS philosophy...

For the moment the objective is 
- Finish and publish this never ending v2
- Polish the product to make it really what it pretend to be.

**Comment by intika** [comment]
Closing this for the moment i will let you know if changes occur ;)

**Comment by intika** [comment]
Project mirrored here https://gitlab.com/intika/Librefox we will see how github evolve first, no plan to move for the moment
