### ISSUE TITLE
How to install on Debian?

### ISSUE THREAD

**Issue by asddsaz** [intika/Librefox-Firefox#14]
**Question**: Which files do I need to execute to install/run?
(sorry for noobish-ness)

**Comment by intika** [comment]
Just use the "Privafox-1.8-Firefox-Linux-63.0.3.tar.bz2" Extract it and launch firefox from inside the extracted directory or create a shortcut let me know if you need help

**Comment by intika** [comment]
To be more precise download 
Privafox-1.8-Firefox-Linux-63.0.3.tar.bz2 (The new version is coming today or tomorrow, you will then need Librefox-2.1-Firefox-Linux-64.0.tar.bz2)... 

1. Extract the archive like any compressed file (right click and extract or open it with ark)
2. Inside the extracted files (folder) double click on firefox... 
3. You can create a shortcut to that firefox fire in your desktop or so...
