### ISSUE TITLE
Firefox EME-free

### ISSUE THREAD

**Issue by dimqua** [intika/Librefox-Firefox#9]
I think it's a good idea to recommend EME-free builds for Windows and macOS instead regular ones.

They can be found here, for example: https://ftp.mozilla.org/pub/firefox/releases/64.0/

**Comment by intika** [comment]
The thing is as i observed on other similar browser a lot of user asking for widevine for netflix or so... indeed eme is disabled by default in librefox... but i would like to leave the choice for the user to enable it back thus using an eme version would not be suitable, never the less its disabled by default... and i added on my local readme a how to enable it back... (will update online version soon)
so i am closing this as wontfix... but any one who willing to harden the settings could apply librefox manually to firefox eme free version

Also if you worry about the eme blob, its not included in librefox, its downloaded by librefox once the settings are turned on, and deleted if the settings are turned off 

Also if the project get more attraction i will may be develop a single extension (for future v3) that include everything about privacy to avoid installing a lot of extensions to get things done right... thus librefox would just need ublock and one single librefox extension to be fully operational... but we are not there yet :)
